import { invoke } from "@tauri-apps/api/core"

export type ResearchCockpitAction =
  | "agentic-ask"
  | "autoresearch-ledger"
  | "autoresearch-status"
  | "dashboard-data"
  | "hypothesis-discover-dry-run"
  | "hypothesis-ask"
  | "candidate-ask-precheck"
  | "data-source-tushare-probe"
  | "hypothesis-evidence-feedback-dry-run"
  | "hypothesis-evidence-feedback-write"
  | "hypothesis-post-mortem-dry-run"
  | "hypothesis-post-mortem-write"
  | "hypothesis-verify"
  | "hypothesis-status-update-write"
  | "export-samples-list"
  | "hypothesis-create-dry-run"
  | "hypothesis-create-write"
  | "hypothesis-supplement-draft"
  | "hypothesis-supplement-dry-run"
  | "hypothesis-supplement-write"
  | "observation-draft-list"
  | "observation-draft-write"
  | "policy-proposal-dry-run"
  | "policy-proposal-write"
  | "self-question-loop-dry-run"
  | "self-question-status"
  | "self-train-next"
  | "self-train-plan-dry-run"
  | "self-train-plan-write"
  | "stock-feedback-status"
  | "stock-feedback-evidence-task-create-dry-run"
  | "stock-feedback-evidence-task-create-write"
  | "stock-feedback-evidence-task-list"
  | "stock-feedback-evidence-task-show"
  | "stock-feedback-run-task-queue-dry-run"
  | "stock-feedback-run-task-queue-write"
  | "stock-feedback-evidence-result-list"
  | "stock-feedback-evidence-result-review-write"
  | "stock-feedback-source-status"
  | "stock-feedback-dlq-list"
  | "stock-feedback-dlq-retry-write"
  | "stock-feedback-dlq-discard-write"
  | "stock-feedback-paper-trade-agent-dry-run"
  | "stock-feedback-paper-trade-agent-write"
  | "stock-feedback-build-dry-run"
  | "stock-feedback-build-write"
  | "stock-feedback-list"
  | "stock-feedback-review-queue"
  | "stock-feedback-review-dry-run"
  | "stock-feedback-review-write"
  | "stock-feedback-collection-task-dry-run"
  | "stock-feedback-collection-task-write"
  | "stock-feedback-collection-result-dry-run"
  | "stock-feedback-collection-result-write"
  | "stock-feedback-paper-trade-status"
  | "stock-feedback-paper-trade-discretionary-review"
  | "stock-feedback-paper-trade-record-dry-run"
  | "stock-feedback-paper-trade-record-write"
  | "stock-feedback-paper-trade-settle-dry-run"
  | "stock-feedback-paper-trade-settle-write"
  | "stock-feedback-bench"
  | "stock-feedback-export-lora-ready"
  | "stock-feedback-verify"
  | "wechat-import-raw-dry-run"
  | "wechat-import-raw-write"
  | "wechat-process"
  | "wechat-source-list"
  | "wechat-status"
  | "watch-dry-run"
  | "watch-write"
  | "validate"
  | "report"

export async function runResearchCockpitCommand<T>(
  projectPath: string,
  action: ResearchCockpitAction,
  args: string[] = [],
): Promise<T> {
  const raw = await invoke<string>("run_research_cockpit_command", {
    projectPath,
    action,
    args,
  })
  return JSON.parse(raw) as T
}
