import { DEFAULT_PROJECT_PATH } from "../core/index.mjs"

export function printHelp() {
  console.log(`Usage:
  npm run codex:ingest -- prepare --source <raw-file> [--project <wiki-root>] [--schema <schema.md>]
  npm run codex:ingest -- convert-source --source <pdf/docx/xlsx/pptx/etc> [--project <wiki-root>] [--output <md-file>] [--overwrite] [--markitdown-bin <bin>] [--ocr-python-bin <python>] [--no-ocr]
  npm run codex:ingest -- api-run --source <raw-file> --model <model> [--project <wiki-root>] [--api-key <key>]
  npm run codex:ingest -- api-run --provider codex --source <raw-file> [--project <wiki-root>] [--model <model>] [--page-concurrency <n>] [--page-write-mode full|patch] [--max-plan-items <n>] [--source-sharding auto|off|force]
  npm run codex:ingest -- batch-run --sources <raw1.md,raw2.md> [--project <wiki-root>] [--provider codex] [--api-concurrency 2] [--page-concurrency 2] [--shard-concurrency 2] [--write]
  npm run codex:ingest -- finalize --report <codex-ingest-report-dir> [--provider codex]
  npm run codex:ingest -- apply --manifest <changes.json> [--project <wiki-root>] [--write]
  npm run codex:ingest -- ask --query "..." [--project <wiki-root>] [--provider codex] [--show-context] [--show-sources] [--include-invalidated] [--agentic] [--profile local-max]
  npm run codex:ingest -- deep-research --topic "..." [--queries "q1,q2"] [--provider codex] [--tavily-api-key <key>] [--write] [--ingest] [--apply-ingest] [--project <wiki-root>]
  npm run codex:ingest -- ask eval [--query "..."] [--expect-paths wiki/概念/xxx.md,raw/研报新闻/xxx.md] [--project <wiki-root>] [--write]
  npm run codex:ingest -- autoresearch program --title "..." --hypothesis "..." [--lanes 光纤链,PCB链] [--editable-artifacts prompt_template,segment_config] [--write]
  npm run codex:ingest -- autoresearch score [--market-feedback-score n] [--evidence-closure-score n] [--attribution-quality-score n] [--novelty-score n] [--leakage-penalty n] [--complexity-penalty n] [--hype-without-order-penalty n]
  npm run codex:ingest -- autoresearch ledger append --program-id <id> --hypothesis "..." --changed-artifact <artifact> --baseline-score n --new-score n [--evidence-gaps "..."] [--future-validation-date YYYY-MM-DD] [--manifest <path>] [--write]
  npm run codex:ingest -- autoresearch ledger [--project <wiki-root>]
  npm run codex:ingest -- autoresearch status [--project <wiki-root>]
  npm run codex:ingest -- autoresearch proposal [--min-score-delta 1] [--changed-artifacts segment_config,market_validator_params,evidence_task_priority] [--write]
  npm run codex:ingest -- autoresearch policy propose [--min-score-delta 1] [--changed-artifacts segment_config,market_validator_params,evidence_task_priority] [--write]
  npm run codex:ingest -- research-os agent status|plan|review|verify [--project <wiki-root>] [--write]
  npm run codex:ingest -- research-os agent step --step-id <id> [--write] [--confirm-human-gate true] [--project <wiki-root>]
  npm run codex:ingest -- hypothesis create --title "..." --theme "..." [--segments MPO,CPO] [--key-variables "..."] [--trigger-conditions "..."] [--invalidation-signals "..."] [--expected-evidence-path "..."] [--related-wiki-pages "wiki/概念/xxx.md"] [--risks "..."] [--next-validation-date YYYY-MM-DD] [--write]
  npm run codex:ingest -- hypothesis list [--status watching] [--theme "..."] [--segment MPO]
  npm run codex:ingest -- hypothesis quality-check [--id <hypothesis-id>] [--status watching] [--theme "..."] [--segment MPO] [--limit 100]
  npm run codex:ingest -- hypothesis evidence-feedback [--id <hypothesis-id>] [--status watching] [--write]
  npm run codex:ingest -- hypothesis evidence-link-drafts [--status watching] [--write]
  npm run codex:ingest -- hypothesis evidence-link-review --draft-id <id> --candidate-index 1 --confirm-human-gate true [--write]
  npm run codex:ingest -- hypothesis evidence-task-draft-list [--gate needs_stock_identity|low_confidence_candidates|candidate_review_ready] [--candidate-limit 5]
  npm run codex:ingest -- hypothesis post-mortem [--id <hypothesis-id>] [--write]
  npm run codex:ingest -- hypothesis verify
  npm run codex:ingest -- hypothesis discover --theme "AI数据中心互联" [--question-count 5] [--concurrency 3] [--sources wiki,raw] [--since 3650d] [--finance-entity-audit-roots <project-or-audit-root>]
  npm run codex:ingest -- hypothesis status-update --id <hypothesis-id> --status strengthening --reason "..." [--event-ref <alert-or-event-ref>] [--write]
  npm run codex:ingest -- hypothesis ask --id <hypothesis-id> [--query "..."] [--agent-concurrency 3] [--agent-timeout-ms 300000]
  npm run codex:ingest -- hypothesis report --id <hypothesis-id> [--write]
  npm run codex:ingest -- hypothesis supplement --title "..." --body "..." [--kind roadshow|spreadsheet|meeting|manual] [--source-refs "..."] [--hypothesis-id <id>] [--write]
  npm run codex:ingest -- hypothesis supplement-draft --body "..." [--selected-sources ima,cninfo,qichacha,tushare] [--source-refs "..."] [--hypothesis-id <id>] [--provider codex|openai]
  npm run codex:ingest -- hypothesis update-from-article --source <raw-or-md-file> [--finance-entity-audit-roots <project-or-audit-root>] [--write]
  npm run codex:ingest -- hypothesis validate --id <hypothesis-id> [--window 20d]
  npm run codex:ingest -- hypothesis watch [--since 1d] [--sources gangtise,wechat,wechat_incremental,hypothesis_supplement,raw,agentic] [--source <raw-file-or-folder>] [--limit 100] [--finance-entity-audit-roots <project-or-audit-root>] [--write]
  npm run codex:ingest -- hypothesis alerts [--status open|closed|all] [--min-alert-level info|watch|important|urgent] [--limit 100]
  npm run codex:ingest -- hypothesis dashboard-data [--json] [--write]
  npm run codex:ingest -- hypothesis wechat-inbox append --message-json '<json-or-jsonl>' [--project <wiki-root>]
  npm run codex:ingest -- hypothesis wechat-inbox sources [--source raw/微信聊天] [--limit 20] [--project <wiki-root>]
  npm run codex:ingest -- hypothesis wechat-inbox import-raw [--source raw/微信聊天] [--since 30m] [--limit 200] [--write] [--project <wiki-root>]
  npm run codex:ingest -- hypothesis wechat-inbox process [--dry-run] [--project <wiki-root>]
  npm run codex:ingest -- hypothesis wechat-inbox status [--project <wiki-root>]
  npm run codex:ingest -- hypothesis wechat-inbox serve [--host 127.0.0.1] [--port 19828] [--token <local-token>] [--project <wiki-root>]
  npm run codex:ingest -- brain remember --type correction|thread|preference|guardrail --text "..." [--project <wiki-root>]
  npm run codex:ingest -- brain status [--project <wiki-root>]
  npm run codex:ingest -- brain resolve --id <id> --result success|failure|uncertain [--project <wiki-root>]
  npm run codex:ingest -- market-validate --prediction "..." --stock <code|name> [--window 20d] [--write]
  npm run codex:ingest -- company-research --stock <code|name> [--from YYYY-MM-DD] [--to YYYY-MM-DD] [--deep] [--plugin-led] [--plugin-led-timeout-ms 600000] [--plugin-review] [--plugin-optimize] [--plugin-review-timeout-ms 600000] [--plugin-optimize-timeout-ms 600000] [--force-investment-banking-review] [--cninfo-event-from YYYY-MM-DD] [--company-provider-timeout-ms 45000] [--cninfo-download-timeout-ms 90000] [--project <wiki-root>]
  npm run codex:ingest -- data-source status
  npm run codex:ingest -- data-source tushare-probe [--stock-code 000001.SZ] [--trade-date YYYY-MM-DD]
  npm run codex:ingest -- data-source qcc-tenders --keyword "数据中心 MPO 光纤" [--pub-date-start YYYY-MM-DD] [--pub-date-end YYYY-MM-DD] [--msg-type 3|4]
  npm run codex:ingest -- daily-loop --mode premarket|postclose|full [--write] [--show-context] [--validate-pending-only]
  npm run codex:ingest -- self-question [--mode premarket|postclose|full] [--question-count 3] [--market-validate off] [--write] [--no-llm-question-planner]
  npm run codex:ingest -- self-question phase-status [--project <wiki-root>]
  npm run codex:ingest -- self-question phase-check [--project <wiki-root>]
  npm run codex:ingest -- self-question phase-advance [--gate <next-action-gate>] [--execute] [--write] [--project <wiki-root>]
  npm run codex:ingest -- self-question phase-run [--max-gates <n>] [--execute] [--write] [--no-phase-run-artifacts] [--project <wiki-root>]
  npm run codex:ingest -- self-question loop [--stages generate,validate,attribute,evidence,policy,policy-regression,policy-regression-execute,policy-regression-feedback,policy-regression-remediation,policy-regression-patches,policy-regression-apply,policy-regression-verify,gate-event,self-train,self-train-plan,self-train-plan-verify,export,export-verify] [--policy-min-occurrences 2] [--execute-policy-regressions] [--policy-regression-concurrency <n>] [--self-train-plan-limit <n>] [--export-verify-concurrency <n>] [--profile local-max] [--apply-policy-regression-patches] [--patch <policy-regression-patches.json>] [--patch-id <id>] [--export-kinds sft,eval] [--export-quality-gate all|eligible|needs_evidence|review_required|negative_sample|high_confidence] [--write] [--self-train-write]
  npm run codex:ingest -- self-question validate [--id <question-id>] [--max-questions 6] [--validation-windows 1,3,5,10,20] [--allow-anchored-external-market] [--external-market-timeout-ms 3000] [--external-market-concurrency 6] [--write]
  npm run codex:ingest -- self-question attribute [--id <validation-id>] [--max-validations 20] [--write]
  npm run codex:ingest -- self-question evidence [--id <attribution-id>] [--max-tasks 100] [--write]
  npm run codex:ingest -- self-question evidence resolve --task-id <task-id> --result confirmed|refuted|insufficient [--source-refs "..."] [--summary "..."] [--write]
  npm run codex:ingest -- self-question policy [--min-occurrences 2] [--write]
  npm run codex:ingest -- self-question policy list
  npm run codex:ingest -- self-question policy regression [--max-policies <n>] [--max-questions-per-policy <n>] [--write]
  npm run codex:ingest -- self-question policy regression evaluate --regression <policy-regressions.json> [--outputs <case-outputs.json>] [--write]
  npm run codex:ingest -- self-question policy regression execute --regression <policy-regressions.json> [--execute] [--concurrency <n>] [--timeout-ms <n>] [--write]
  npm run codex:ingest -- self-question policy regression feedback --execution <policy-regression-execution.json> [--write]
  npm run codex:ingest -- self-question policy regression remediation --feedback <policy-regression-feedback.json> [--write]
  npm run codex:ingest -- self-question policy regression remediation approve|reject --remediation <policy-regression-remediations.json> --remediation-id <id> [--reviewer <name>] [--note "..."] [--write]
  npm run codex:ingest -- self-question policy regression remediation patches [--remediation-id <id>] [--write]
  npm run codex:ingest -- self-question policy regression remediation patches apply --patch <policy-regression-patches.json> --patch-id <id> [--reviewer <name>] [--note "..."] [--write]
  npm run codex:ingest -- self-question policy approve|reject --policy-id <proposal-policy-id> [--proposal <policy-proposals.json>] [--reviewer <name>] [--note "..."] [--write]
  npm run codex:ingest -- self-train [--project <wiki-root>] [--include-reviewed] [--write]
  npm run codex:ingest -- self-train actions [--status open|reviewed|approved|rejected|resolved|all] [--order-by createdAt|priority] [--limit 50] [--rule R8] [--target "..."] [--project <wiki-root>]
  npm run codex:ingest -- self-train next [--limit 5] [--status open] [--project <wiki-root>]
  npm run codex:ingest -- self-train plan [--limit 5] [--status open] [--write] [--project <wiki-root>]
  npm run codex:ingest -- self-train plan list [--limit 20] [--project <wiki-root>]
  npm run codex:ingest -- self-train plan verify [--plan <plan.json>] [--limit 20] [--project <wiki-root>]
  npm run codex:ingest -- self-train review --id <action-id> --action approve|reject|resolve [--reviewer <name>] [--quality reviewed|eligible|review_required|high_confidence] [--evidence-ref <ref1,ref2>] [--note "..."] [--write]
  npm run codex:ingest -- stock-feedback status [--project <wiki-root>]
  npm run codex:ingest -- stock-feedback build-trajectories [--write] [--project <wiki-root>]
  npm run codex:ingest -- stock-feedback bench [--write] [--limit 200] [--project <wiki-root>]
  npm run codex:ingest -- stock-feedback list [--validation-target expectation_trade|fundamental_closure|priced_in_risk|disconfirmation] [--quality-gate expectation_validated|fundamental_validated|priced_in_validated|disconfirmed_validated|needs_evidence|review_required|high_confidence] [--market-pattern event_expectation_front_run|low_absorption_breakout|priced_in_late_entry|failed_catalyst_one_day_hype|fundamental_closure_confirmation] [--stock <code|name>] [--hypothesis "..."] [--date YYYY-MM-DD] [--limit 100]
  npm run codex:ingest -- stock-feedback review-queue [--include-reviewed] [--limit 100] [--project <wiki-root>]
  npm run codex:ingest -- stock-feedback review --trajectory-id <id> --action approve_for_adapter|approve_paper_adapter_candidate|route_to_eval|route_to_preference|route_to_sft|needs_evidence|reject_for_adapter|mark_entry_wrong|mark_priced_in [--reviewer <name>] [--note "..."] [--write]
  npm run codex:ingest -- stock-feedback collection-task [--market-pattern event_expectation_front_run|low_absorption_breakout|priced_in_late_entry|failed_catalyst_one_day_hype|fundamental_closure_confirmation] [--profit-credit pattern_execution_supported|execution_risk_negative|failed_expectation_negative] [--write]
  npm run codex:ingest -- stock-feedback collection-result [--draft-id <id>|--task-id <id>|--market-pattern <pattern>|--profit-credit <credit>] --result confirmed|refuted|insufficient [--evidence-refs "ref1,ref2"] [--summary "..."] [--write]
  npm run codex:ingest -- stock-feedback evidence-task create --stock-code <code> --task-type market_data|financial_metrics|announcement|tenders|institutional_flow|limit_up_analysis|general --target-fields "field1,field2" [--source hypothesis|self_question|stock_feedback|manual] [--preferred-sources tushare,cninfo,qcc,web] [--source-refs "..."] [--tool-state-refs "..."] [--write]
  npm run codex:ingest -- stock-feedback evidence-task list [--status pending|awaiting_review|completed|failed|dlq] [--task-type market_data] [--stock <code|name>]
  npm run codex:ingest -- stock-feedback evidence-task show --task-id <id>
  npm run codex:ingest -- stock-feedback run-task-queue [--task-id <id>] [--limit 10] [--tavily-max-results 5] [--write]
  npm run codex:ingest -- stock-feedback evidence-result list [--status completed|awaiting_review|rejected|failed] [--task-id <id>]
  npm run codex:ingest -- stock-feedback evidence-result review --result-id <id> --action approve|reject|needs_more_evidence [--reviewer <name>] [--note "..."] [--write]
  npm run codex:ingest -- stock-feedback source-status
  npm run codex:ingest -- stock-feedback dlq list [--status open|all]
  npm run codex:ingest -- stock-feedback dlq retry --dlq-id <id>|--task-id <id> [--note "..."] [--write]
  npm run codex:ingest -- stock-feedback dlq discard --dlq-id <id>|--task-id <id> [--note "..."] [--write]
  npm run codex:ingest -- stock-feedback execution-result import --from-delivery-notes|--from-position-tracking [--date YYYY-MM-DD] [--auto-market-evidence] [--write]
  npm run codex:ingest -- stock-feedback execution-result validate [--auto-market-evidence] [--write]
  npm run codex:ingest -- stock-feedback execution-result list [--status confirmed|reviewed|needs_review] [--stock <code|name>] [--pnl-scope closed_position|partial_exit|holding_snapshot]
  npm run codex:ingest -- stock-feedback execution-result review --artifact-id <id> --action confirm_realized_execution|mark_partial_exit|mark_holding_snapshot_only|mark_needs_reconciliation|reject_execution_result [--reviewer <name>] [--note "..."] [--write]
  npm run codex:ingest -- stock-feedback execution-result verify [--project <wiki-root>]
  npm run codex:ingest -- stock-feedback paper-trade-agent candidates [--limit 12] [--write]
  npm run codex:ingest -- stock-feedback paper-trade status [--limit 8] [--project <wiki-root>]
  npm run codex:ingest -- stock-feedback paper-trade record --track rule_baseline|llm_discretionary --stock-code <code> --entry-date YYYY-MM-DD --entry-price <price> [--exit-date YYYY-MM-DD] [--exit-price <price>] [--microstructure-date YYYY-MM-DD] [--realized-pnl-pct <pct>] [--max-drawdown-pct <pct>] [--holding-days <n>] [--source-refs "self-question:..."] [--evidence-refs "price-sql:..."] [--write]
  npm run codex:ingest -- stock-feedback paper-trade settle --paper-trade-id <id> --exit-date YYYY-MM-DD --exit-price <price> [--realized-pnl-pct <pct>] [--max-drawdown-pct <pct>] [--holding-days <n>] [--exit-reason "..."] [--evidence-refs "price-sql:..."] [--write]
  npm run codex:ingest -- stock-feedback paper-trade discretionary-review [--limit 8] [--project <wiki-root>]
  npm run codex:ingest -- stock-feedback export-lora-ready [--validation-target expectation_trade|fundamental_closure|priced_in_risk|disconfirmation] [--quality-gate high_confidence] [--limit 500] [--write]
  npm run codex:ingest -- stock-feedback verify [--project <wiki-root>]
  npm run codex:ingest -- export-samples --kind sft|preference|eval [--quality-gate all|eligible|needs_evidence|review_required|negative_sample|high_confidence|expectation_validated|fundamental_validated|priced_in_validated|disconfirmed_validated] [--project <wiki-root>]
  npm run codex:ingest -- export-samples list [--kind sft|preference|eval] [--quality-gate all|eligible|needs_evidence|review_required|negative_sample|high_confidence|expectation_validated|fundamental_validated|priced_in_validated|disconfirmed_validated] [--limit 20] [--project <wiki-root>]
  npm run codex:ingest -- export-samples verify [--kind sft|preference|eval] [--quality-gate all|eligible|needs_evidence|review_required|negative_sample|high_confidence|expectation_validated|fundamental_validated|priced_in_validated|disconfirmed_validated] [--limit 20] [--verify-concurrency 8] [--profile local-max] [--project <wiki-root>]
  npm run codex:ingest -- hygiene audit|plan|apply [--project <wiki-root>] [--keep-days 14] [--write]
  npm run codex:ingest -- temporal-facts audit [--project <wiki-root>] [--top-n 50] [--write]
  npm run codex:ingest -- concepts audit [--project <wiki-root>] [--top-n 100] [--write]

Defaults:
  --project ${DEFAULT_PROJECT_PATH}

Notes:
  prepare writes only .llm-wiki/codex-ingest reports.
  convert-source writes a generated Markdown sidecar next to the source by default (e.g. report.pdf -> report.markitdown.md); if a PDF has no text layer, it falls back to macOS Vision OCR unless --no-ocr is set. ingest/apply still never write raw/.
  api-run writes staged artifacts (analysis.md, plan.json, files/**, changes.json) and dry-runs the manifest.
  batch-run runs multiple api-run jobs concurrently, then finalizes/conflict-checks/applies one source at a time when --write is set. Live wiki writes are always single-writer; --write-concurrency is fixed at 1.
  finalize resumes after page FILE blocks exist and only regenerates housekeeping/changes.json/dry-run.
  --provider codex uses the local Codex CLI login instead of OPENAI_API_KEY.
  --page-concurrency controls parallel FILE-block generation; defaults to 1.
  --page-write-mode full|patch controls Stage 3 update-page output; defaults to full. patch asks the model for section patch operations, applies them locally onto the existing page, and falls back to full-page generation per page on any patch failure. Create pages and the source archive always use full generation. Patch raw outputs are kept as files/patch-*.md audit artifacts.
  --judgments enables judgment-ledger planning in Stage 2: the plan may include judgmentWrites (kind thesis/expectation/lesson/stance, status held/revised/invalidated/expired) that append to data/facts/judgments.jsonl on apply --write, mirroring factWrites (deterministic ids, dedup, supersedes revision chain, dry-run review). stance judgments default to visibility personal. apply always understands judgmentWrites even without this flag.
  embeddings build|status maintains a semantic index of formal wiki pages at .llm-wiki/embeddings/wiki-pages.json (incremental: unchanged pages are reused by text hash). Requires OPENAI_API_KEY or --embedding-api-key; --embedding-model defaults to text-embedding-3-small.
  --embedding-routing on prepare/api-run/batch-run merges semantic hits (whole-source plus per-segment) into candidate wiki pages to improve routing precision. Missing index or API key degrades to lexical candidates with a warning; it never blocks ingest. The routing summary is recorded in candidate-pages.json.
  apply --write auto-refreshes the embedding index incrementally when it touches indexed wiki pages and the index already exists (report field embeddingIndexRefresh); missing key or refresh errors are recorded but never block apply.
  --source-sharding auto|off|force controls large WeChat sentiment shard analysis; defaults to auto.
  --shard-concurrency controls parallel shard analysis for large WeChat sources; defaults to 3.
  --max-shard-chars controls target shard prompt size; defaults to 45000.
  --source-retention mainline-index keeps a programmatic 分时主线索引 in source archives. Large WeChat files should use CLI api-run; the desktop Sources button still uses the older 4-stage path.
  --max-plan-items, --max-create-pages, and --max-update-pages record soft plan-budget warnings in plan-budget.json; they do not stop normal ingest.
  ask is read-only. Use --show-context to print retrieval hits; use --show-sources to print source routing/native query summaries.
  ask agentic controls: --agentic enables concurrent evidence/counterevidence/market/strategy agents before final adjudication; --agent-concurrency defaults to 3; --agent-timeout-ms bounds each provider call; artifacts write to .llm-wiki/agent-runs unless --no-agent-artifacts is present.
  performance profile: --profile local-max keeps defaults unchanged unless requested, then raises bounded local concurrency for agentic ask, self-question loop regression/export verification, and export-samples verify; explicit concurrency flags still win.
  ask eval is read-only by default and reports retrieval recall/relevance/source coverage/raw-noise/structure scores; --write stores only .llm-wiki/eval/*.json.
  ask source controls: --source-k 3 --sources auto|wiki,raw,graph,facts,brain,stock-price --graph-depth auto|1|2 --top-brain 8 --sql-limit 200 --include-invalidated.
  deep-research mirrors the desktop Deep Research panel from CLI: Tavily search plus local ask retrieval feeds a synthesis draft under .llm-wiki/deep-research. --write saves the reviewed page shape to wiki/queries with origin: deep-research. --ingest runs staged ingest on that saved page; --apply-ingest additionally applies the staged manifest, so use it only when you intend formal wiki writes. Tavily credentials come from --tavily-api-key, TAVILY_API_KEY, or the trading-wiki Tavily keychain item.
  autoresearch is Trading Autoresearch Lite: it creates natural-language research programs, locked-score experiment records, review-gated keep/discard ledgers, and proposed policy changes under .llm-wiki/research-programs and .llm-wiki/experiments only. It cannot write wiki/, raw/, or real trading actions; high-confidence still requires reviewed evidence-backed samples.
  research-os agent is the Codex-orchestrated multi-agent backend. It exposes status/plan/step/review/verify for the chat-window SupervisorAgent, writes only .llm-wiki/research-os/agent-runs with --write, and step --write requires --confirm-human-gate true. It never accepts arbitrary shell commands, writes formal wiki/raw, or triggers real trading actions. review supports read-only operator filters: --queue <queueId>, --source primary_step|secondary_queue, --operator-next-step <step>, --dry-run-ready true|false, --write-ready true|false, and --action-limit <n> narrow only nextHumanGateActions while preserving the full nested review context. review also emits nextHumanGateActionRunbook with copy-paste shell dry-run commands, input gaps, and write templates that remain HumanGate-gated.
  hypothesis is Phase 5B/5C Hypothesis Library + Watchtower: create/list/report/update/validate auditable investment hypotheses, route new source events, list alerts, and emit dashboard data. Writes are dry-run by default and limited to .llm-wiki/hypotheses, .llm-wiki/hypothesis-events, .llm-wiki/hypothesis-alerts, .llm-wiki/hypothesis-dashboard, .llm-wiki/hypothesis-reports, and .llm-wiki/hypothesis-supplements; it never writes wiki/, raw/, prompts, segment config, market validator params, or trading actions. hypothesis watch can use --llm-review auto|off|force to review only the small candidate set after deterministic filtering; LLM review only changes dry-run suggestions, never hypothesis status. Use --compact for cockpit-style output that keeps summaries/events/alerts/candidates but omits the full scanned source list. --finance-entity-audit-roots, or TRADING_WIKI_FINANCE_ENTITY_AUDIT_ROOTS, can point to another wiki project or sag-entity-audit directory so Watchtower can reuse finance keyword/entity tables without copying them into the current project. hypothesis supplement is the manual/roadshow/spreadsheet evidence window for filling gaps before Watchtower scanning. wechat-inbox is the local incremental message intake path for hypothesis signals; it writes only .llm-wiki/wechat-inbox and Watchtower can scan processed messages with --sources wechat_incremental. import-raw is the no-WeChat-login fallback: it reads raw/微信聊天 Markdown/TXT/JSONL files and, with --write, appends normalized wechat-increment-v1 records to .llm-wiki/wechat-inbox/incoming without modifying raw/ or wiki/.
  daily-loop controls: --question-count <n> --lookback-days 30 --max-stocks-per-question 8 --max-existing-validations <n> --validation-windows 1,3,5,10,20 --market-validate auto|off|tencent|eastmoney --validate-pending-only.
  daily-loop questions are planned by the provider LLM first; rules/templates are only fallback.
  self-question generates structured self-question-v1 records for the recursive loop. It is dry-run by default and writes only data/brain/questions.jsonl with --write.
  self-question phase-status is read-only and reports the current recursive AI phase, artifact counts, sample gates, Phase 5 readiness, and remaining manual gates.
  self-question phase-check is read-only and exits non-zero when Phase 5 readiness is blocked; use it as an automation/CI gate before any unattended recursive run.
  self-question phase-advance selects one nextAction from phase-status and is dry-run by default; pass --execute and, for write gates, --write to run exactly one mapped stage/function.
  self-question phase-run plans several nextActions in dry-run mode and, with --execute, advances at most --max-gates gates while re-reading phase-status between gates; repeated gates stop the run. It writes an audit manifest under .llm-wiki/self-question-runs unless --no-phase-run-artifacts is present.
  self-question loop orchestrates generate/validate/attribute/evidence/policy/policy-regression/policy-regression-execute/policy-regression-feedback/policy-regression-remediation/policy-regression-patches/policy-regression-apply/policy-regression-verify/gate-event/self-train/self-train-plan/self-train-plan-verify/export/export-verify stages and writes an audit manifest under .llm-wiki/self-question-runs unless --no-loop-artifacts is present. The evidence, policy, policy-regression, policy-regression-execute, policy-regression-feedback, policy-regression-remediation, policy-regression-patches, policy-regression-apply, policy-regression-verify, gate-event, self-train-plan, self-train-plan-verify, and export-verify stages are opt-in through --stages and write only their declared .llm-wiki artifacts, or data/brain/policies.jsonl plus data/brain/self_training_events.jsonl for policy-regression-apply, or data/brain/self_training_events.jsonl for gate-event, when --write is present; export-verify and self-train-plan-verify are read-only gates. The policy-regression-execute and policy-regression-verify stages only run commands with --execute-policy-regressions; otherwise they record plans. Both stages record planned/passed/needs_remediation verdicts; command failures, timeouts, failed assertions, or skipped assertions route to feedback/remediation without treating the loop as a CLI crash. Use --policy-regression-concurrency to run local regression case commands concurrently while preserving stable result order. The gate-event stage records open planned/needs_remediation gateSummary items as long-term learning events. self-train-plan can convert in-memory self-train actions from the same loop into .llm-wiki/self-training-plans without forcing data/brain writes; self-train-plan-verify checks the just-written plan when present and otherwise gates missing plans as planned. The policy-regression-apply stage only applies reviewed patch candidates with --apply-policy-regression-patches; otherwise it records a skipped stage. The export stage only materializes sample files when --write is present and can pass --export-quality-gate to keep loop-generated exports aligned with standalone export-samples; self-train remains dry-run unless --self-train-write is also present.
  self-question validate converts planned self-question records into market-feedback validation records. It is dry-run by default and writes only data/brain/validations.jsonl with --write. Anchored validation is SQL-only by default; --allow-anchored-external-market lets external kline act as an explicit fallback when local SQL has no post-anchor rows. For stuck live feedback, prefer a small first retry such as --max-questions 1 --validation-windows 1 --external-market-timeout-ms 3000.
  self-question attribute classifies self-question market-feedback validations as confirmed/price_only/divergent/disconfirmed/insufficient. It is dry-run by default and writes only data/brain/attributions.jsonl with --write.
  self-question evidence collects price_only attribution evidenceTasks into a pending CNINFO/QCC/Tushare task queue. It is dry-run by default and writes only .llm-wiki/evidence-tasks with --write.
  self-question evidence resolve records completed evidence task results. It is dry-run by default and writes only data/brain/evidence_results.jsonl with --write.
  self-question policy proposes reviewable policy updates from repeated attribution gaps. It is dry-run by default and writes only .llm-wiki/policy-proposals with --write. self-question policy regression exports active-policy eval cases and writes only .llm-wiki/policy-regressions with --write; regression evaluate grades supplied case outputs and writes only .llm-wiki/policy-regression-results with --write; regression execute plans by default, runs commands only with --execute, records planned/passed/needs_remediation verdicts, and writes only .llm-wiki/policy-regression-executions with --write; regression feedback turns failed/skipped regression execution results into reviewable feedback and writes only .llm-wiki/policy-regression-feedback with --write; regression remediation turns feedback into reviewable fix proposals and writes only .llm-wiki/policy-regression-remediations with --write; remediation approve/reject writes explicit review events to data/brain/self_training_events.jsonl with --write and never auto-applies prompt/policy/sample changes; remediation patches exports approved review events as manual patch candidates and writes only .llm-wiki/policy-regression-patches with --write; remediation patches apply appends an active policy revision plus apply event only with --write, remains manual/idempotent, and does not write wiki/raw. self-question policy approve/reject writes explicit review events; approve also appends active policies to data/brain/policies.jsonl only with --write.
  self-train actions is a read-only ledger over persisted self-training-action events and their latest review status; self-train next is the same ledger filtered to open actions and sorted by priority for handoff. self-train plan converts the next open actions into a non-executing task plan and writes only .llm-wiki/self-training-plans with --write; self-train plan list reads those plan artifacts without writing; self-train plan verify is read-only and checks plan artifacts for non-execution, count consistency, structure, and obvious unredacted secret patterns before a human or later executor uses them. self-train review appends a self-training-action-review event only with --write; reviewed actions are hidden from later self-train suggestions unless --include-reviewed is present. A review is not high-confidence by default; --quality high_confidence requires --evidence-ref and is the only review path that can feed high_confidence exports.
  stock-feedback is the training flywheel data layer. It converts self-question market feedback into stock-feedback-trajectory-v1 records, then benchmark cases, review events, PEFT-ready adapter candidates, V2 paper-trade simulation evidence, and v0.13 evidence runner artifacts. It separates expectation_trade from fundamental_closure: market-traded expectations can become expectation_validated without order/announcement/financial evidence, while fundamental_validated still requires fundamental evidence. evidence-task/run-task-queue is the thin-slice Evidence Runner: tasks, results, runs, DLQ, and source health write only under .llm-wiki/stock-feedback/** with --write and never mutate wiki/, raw/, data/brain, or real trading ledgers. paper-trade writes only simulated ledgers under .llm-wiki/stock-feedback/paper-trades/** with ledgerKind=paper_trade; it never writes or mutates real trade ledgers. approve_paper_adapter_candidate is the human-review path for profitable paper trades: it can enter LoRA-ready as a low-weight adapter candidate, but it is not a real realized-PnL approval. review-queue is read-only; review writes an explicit human routing event only with --write. Writes are dry-run by default and limited to .llm-wiki/stock-feedback/** with --write; it never writes wiki/, raw/, or trading actions.
  stock-feedback execution-result imports real execution artifacts from raw/交割单 and position-tracking cross-checks. raw/交割单 is the primary fill evidence; wiki/position-tracking.md is summary/snapshot evidence only. Writes are dry-run by default and limited to .llm-wiki/stock-feedback/execution-results/** with --write; it never mutates wiki/, raw/, data/brain, or real trading actions.
  export-samples defaults to --quality-gate all; use --quality-gate eligible or high_confidence to keep unverified price_only samples out of high-confidence training exports, or stock-feedback gates such as expectation_validated/priced_in_validated for target-specific samples. Each export writes a sibling .manifest.json with quality/source distributions and sampleRefs, and appends .llm-wiki/exports/training/export-ledger.jsonl as the cross-batch index; export-samples list reads that ledger without writing; export-samples verify checks ledger/jsonl/manifest existence and counts before training use with bounded concurrency; repeated same-day exports keep prior batches by adding a timestamp or sequence suffix.
  brain/market/self-train commands write only data/brain or .llm-wiki/exports when explicitly invoked; ask remains read-only.
  company-research writes only .llm-wiki/company-research reports, model workbooks, and wiki write candidates; --deep adds document-extract/business-breakdown/deep-report artifacts, searches official event/IR lookbacks, uses SSE fallback for SH listings, records provider progress/status, and never writes raw/ or formal wiki/ pages. --plugin-led lets Data Analytics and Public Equity Investing directly produce the model analysis and a complete deep-research report from evidence artifacts, retries Public Equity once when the report is incomplete, and writes plugin-led/report-completeness.json plus publish-readiness.json; Investment Banking only runs for transaction/capital-markets triggers or --force-investment-banking-review. --plugin-review runs real plugin-tagged Codex subprocess reviews for Data Analytics and Public Equity Investing, and only runs Investment Banking when triggered. --plugin-optimize uses the plugin reviews to generate an optimized publish-candidate report plus publish-readiness gate under plugin-review/.
  daily-loop writes only data/brain and .llm-wiki/daily-research or .llm-wiki/wiki-feedback when --write is present.
  hygiene audit/plan are read-only; hygiene apply only removes old successful .llm-wiki/codex-ingest report dirs with --write.
  temporal-facts audit scans wiki/**/*.md and writes only .llm-wiki/temporal-facts when --write is present.
  concepts audit scans wiki/概念/**/*.md and writes only .llm-wiki/concept-governance when --write is present.
  apply is dry-run unless --write is present.
  raw/ is never written by ingest/apply; convert-source may write a user-requested Markdown sidecar.
`)
}
